name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint with Gradle
        run: ./gradlew raccoon:lint

  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean with Gradle
        run: ./gradlew clean
      - name: Assemble with Gradle
        run: ./gradlew raccoon:assemble


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean with Gradle
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew app:build

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: IntegrationTestsMoshi
        run: ./gradlew raccoon:testDebugUnitTest  --tests "me.iamjoseph.raccoon.IntegrationTestsMoshi"
      - name: IncludeIntegrationTestsMoshi
        run: ./gradlew raccoon:testDebugUnitTest  --tests "me.iamjoseph.raccoon.IncludeIntegrationTestsMoshi"
      - name: IntegrationTestsGson
        run: ./gradlew raccoon:testDebugUnitTest  --tests "me.iamjoseph.raccoon.IntegrationTestsGson"
      - name: IncludedIntegrationTestsGson
        run: ./gradlew raccoon:testDebugUnitTest  --tests "me.iamjoseph.raccoon.IncludedIntegrationTestsGson"


  androidTests:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Raccon UI Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
